# Generated by Django 5.1.1 on 2024-09-19 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0002_answer_slug_category_slug_question_slug_quiz_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='slug',
        ),
    ]
