# Generated by Django 5.1.1 on 2024-09-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0003_remove_useranswer_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useranswer',
            old_name='answer',
            new_name='selected_answer',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='answeredAt',
        ),
        migrations.AddField(
            model_name='useranswer',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
